In [1]:
import numpy as np

#矩阵定义
a = np.mat('1 2;3 4')
b = np.mat('1 3 6;1 0 1;0 1 1')
c = np.mat('1 2 3 ; 4 5 6 ; 7 8 9')

$C_{ij}$表示$a_{ij}$的代数余子式，i+j是偶数时，行列式取正号；奇数时取负号。  
$det(A) = \sum_{i=1}^n a_{1i}C_{1i}$

In [2]:
#计算二阶、三阶行列式
det_a = np.linalg.det(a)
det_b = np.linalg.det(b)
det_c = np.linalg.det(c)

print('a = \n {0}\n det(a) = {1}'.format(a,np.round(det_a)))
print('b = \n {0}\n det(b) = {1}'.format(b,np.round(det_b)))
print('c = \n {0}\n det(c) = {1}'.format(c,np.round(det_c)))

a = 
 [[1 2]
 [3 4]]
 det(a) = -2.0
b = 
 [[1 3 6]
 [1 0 1]
 [0 1 1]]
 det(b) = 2.0
c = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 det(c) = 0.0


In [1]:
import numpy as np
from scipy import linalg
A = np.array([[1,0,0],
              [0,2,0],
              [0,0,5]])
A_n = linalg.inv(A)
print(A_n)
print(np.dot(A,A_n))

[[ 1.  -0.  -0. ]
 [ 0.   0.5 -0. ]
 [ 0.   0.   0.2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
