In [1]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [2]:
arr1

array([1., 2., 3.])

In [3]:
arr2

array([1, 2, 3], dtype=int32)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [8]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])